name: Package Classic addon

on:
  push:
    branches:
      - master
    tags:
      - '**-classic'
    paths-ignore:
      - 'ldoc.ltp'

env:
  GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
  WAGO_TOKEN: ${{ secrets.WAGO_API_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout addon
        uses: actions/checkout@v1
        with:
          fetch-depth: 100

      - name: LUA Lint
        uses: davidcraig/action-wow-lint@v1.0.1
        with:
            path-to-files: 'main.lua'

      - name: Package Classic
        uses: BigWigsMods/packager@master
        with:
          args: release.sh -a kRNLO4Go -m pkgmeta.yml

      - name: Package BC Classic
        uses: BigWigsMods/packager@master
        with:
          args: release.sh -g bcc -a kRNLO4Go -m pkgmeta.yml
